version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./compose/develop/Dockerfile
    ports:
      - "5500:5500"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=akam1022AK
      - DB_NAME=express-reviews
      - DB_PORT=5432
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=akam1022AK
      - POSTGRES_DB=express-reviews
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
